import turtle
wn = turtle.Screen()
q1 = turtle.Turtle()
q2 = turtle.Turtle()
q3 = turtle.Turtle()
q4 = turtle.Turtle()
q1.hideturtle()
q2.hideturtle()
q3.hideturtle()
q4.hideturtle()
q1.penup()
q2.penup()
q3.penup()
q4.penup()
q1.goto(0,-50)
q2.goto(0,-50)
q3.goto(0,-50)
q4.goto(0,-50)
q1.speed(0)
q2.speed(0)
q3.speed(0)
q4.speed(0)
clist = ["blue","red","green","black"]
for j in range(0,4):
    col = clist[j]
    q1.color(col)
    q2.color(col)
    q3.color(col)
    q4.color(col)
    x = 30
    y = 1
    for i in range(0,28):
        q1.penup()
        q2.penup()
        q3.penup()
        q4.penup()
        q2.left(90)
        q3.right(90)   
        q1.forward(x) #goes forward and then turns up
        q2.forward(x) #goes back
        q3.forward(x) #goes down
        q4.forward(x) #goes forward and then turns down
        q1.left(90)
        q2.left(90)
        q3.right(90)
        q4.right(90)
        q1.pendown()
        q2.pendown()
        q3.pendown()
        q4.pendown()
        q1.forward(x)
        q2.forward(x)
        q3.forward(x)
        q4.forward(x)
        q1.left(90)
        q2.left(90)
        q3.right(90)
        q4.right(90)
        q1.forward(x)
        q2.forward(x)
        q3.forward(x)
        q4.forward(x)
        q1.penup()
        q2.penup()
        q3.penup()
        q4.penup()
        q1.left(90)
        q2.left(90)
        q3.right(90)
        q4.right(90)
        q1.forward(x)
        q2.forward(x)
        q3.forward(x)
        q4.forward(x)
        q1.left(90)
        q4.right(90)
        x = x + y
        y = y + 1
